### PR TITLE
replace copy with copySync

### PR DESCRIPTION
**Pull request by piscium2010**
Fix: https://github.com/vladshcherbin/rollup-plugin-copy/issues/43

minor change but fix annoying issue

### CODE REVIEW

**Comment by PascalLuginbuehl** [comment]
This fixes our problem also. It would be nice to have this merged and released as soon as possible.
```
(copy plugin) Error: EBUSY: resource busy or locked, unlink 'C:\www\tsdx-npm-react\dist\media\icons\apps.svg'
Error: EBUSY: resource busy or locked, unlink 'C:\www\tsdx-npm-react\dist\media\icons\apps.svg'
```

**Comment by vladshcherbin** [comment]
@piscium2010, @PascalLuginbuehl can you try upgrading `fs-extra` dependency to v9 and see if `fs.copy` still gives error in your project? Thanks

**Comment by PascalLuginbuehl** [comment]
@vladshcherbin I upgraded fs-extra to v9.0.1. Unfortunately, it does not fix our problem and I get the same error message.

**Comment by piscium2010** [comment]
@vladshcherbin I confirmed that fs-extrav9.0.1 still causes problem.

**Comment by yhy-1** [comment]
I'm also having this issue, is there anyway to get this merge in. 

> This fixes our problem also. It would be nice to have this merged and released as soon as possible.
> 
> ```
> (copy plugin) Error: EBUSY: resource busy or locked, unlink 'C:\www\tsdx-npm-react\dist\media\icons\apps.svg'
> Error: EBUSY: resource busy or locked, unlink 'C:\www\tsdx-npm-react\dist\media\icons\apps.svg'
> ```

**Review by ZipJo — APPROVED** [review]

**Comment by ZipJo** [comment]
@vladshcherbin would be great to have this merged in - this solves the only bug I'm facing with this package atm.

**Comment by EduardoMichel** [comment]
@vladshcherbin 
Can we not get this merged?

**Comment by ellismonva** [comment]
Can we merge this? I'm having an issue here when trying to copy a folder.

**Review by petergray-maker — APPROVED** [review]

**Review by AntoineKM — APPROVED** [review]

**Review by raulmarindev — APPROVED** [review]

**Comment by raulmarindev** [comment]
@vladshcherbin Hello! I believe quite a few people are waiting for this. 🙂

**Comment by vladshcherbin** [comment]
Released in 3.5.0 under `copySync` option.

I've tried to replicate the error locally with no luck, hopefully this option will help resolve the errors you have, guys. I'd be happy to see a reproduction repo to better tackle the reason.

Thank you ♥️

**Pull request merged**
