### PR TITLE
Keep directory structure using the flattened mode

### PR DESCRIPTION
**Pull request by hrodriguez758**
The merge request solve the issue https://github.com/vladshcherbin/rollup-plugin-copy/issues/32

### CODE REVIEW

**Comment by hrodriguez758** [comment]
@mario-d-s @vladshcherbin Check it and let me know if you need to know something or if I have to change anything.

**Comment by LarsDenBakker** [comment]
+1 this is a very useful feature to have

**Comment by alejandroclaro** [comment]
@vladshcherbin anything wrong with this? 

This is really helpful. +1

**Comment by vladshcherbin** [comment]
Resolves #32

**Comment by vladshcherbin** [comment]
@hrodriguez758 Thank you ❤️ 

I've slightly updated it and released in 3.2.0. Please test in your projects to see if it's working as expected.

**Comment by LarsDenBakker** [comment]
@vladshcherbin it looks like it's removing the first part of the directory structure, for example if I copy a file `/node_modules/foo/bar/assets/my-image.png` it gets copied as `foo/bar/assets/my-image.png`

**Comment by hrodriguez758** [comment]
@LarsDenBakker That happened because the code takes the first folder as the root source `(src/**)` and that folder name is replaced by the dest source `(dist/**)`. However, you can add the `node_modules` path in the destination source and the code will append it with `foo/bar/assets/my-image.png`. Check it and let me know if you still have an issue with the current behavior.

**Comment by LarsDenBakker** [comment]
That seems like a bug to me, the option advertises to keep the directory structure when it is actually not. I am copying from multiple directories, so now I need to split up my glob and manually prefix each directory.

**Pull request merged**
