### PR TITLE
fix: use rollup's addWatchFile API to watch target sources

### LINKED ISSUE #5: Support rollup's watch mode
When running rollup in watch mode, if a change is made to a copied asset, the modified asset should be copied again to the target directory.  Right now one has to kill the watch process and re-run it for the copy to be done.  It breaks the "mental flow" of development since one has to constantly remember that changes made to the edited buffer are not propagated automatically, unlike other sources.  How many times have I reloaded the web page, wondered why it's not working, before realizing I forgot to kill the watch process and rerun it?

### PR DESCRIPTION
**Pull request by bennypowers**
fixes #5 
closes #30

### CODE REVIEW

**Comment by bennypowers** [comment]
If anyone needs a simple solution in the mean time

https://github.com/bennypowers/rollup-plugin-watch-assets

**Comment by guidobouman** [comment]
Is there a reason this was not merged in? It seems like a very reasonable feature to add within this package, instead of adding an extra dependency?

**Comment by guidobouman** [comment]
@vladshcherbin ☝️

**Comment by gerwinbrunner** [comment]
Any update on this?

**Pull request closed without merging**
