### PR TITLE
Support multiple destination on copy

### PR DESCRIPTION
**Pull request by toxic-johann**
In some situation, we may want to copy a file to multiple place. So I think it is better to support multiple destination copy by array value.

### CODE REVIEW

**Comment by toxic-johann** [comment]
Is the project still being maintained?

**Comment by ggviana** [comment]
This would be a good feature, please merge.

**Comment by toxic-johann** [comment]
@ggviana You can take https://github.com/toxic-johann/rollup-plugin-fse-copy as a temporary solution.

**Comment by marverix** [comment]
I have created this if you want https://github.com/marverix/rollup-plugin-copier . And I'm going to maintain it. So feel free to contribute and use it.

**Comment by vladshcherbin** [comment]
Hey

I'm the new maintainer of this project. A new version (1.0.0) was published a few days ago, it was rewritten so I couldn't merge this one. I had plans to add this later this week, but suddenly a new PR was added for updated version of the package.

So, this one is resolved in https://github.com/vladshcherbin/rollup-plugin-copy/pull/17 and released in 1.1.0.

Thank you 😉

**Pull request closed without merging**
